### ISSUE TITLE
Issues on pipe in named pipe

### ISSUE THREAD

**Issue by twoobao** [sean1832/Portal#8]
![螢幕擷取畫面 2024-08-31 151306](https://github.com/user-attachments/assets/b6d42a86-ef59-4636-954b-a1abd52d0472)
![螢幕擷取畫面 2024-08-31 150754](https://github.com/user-attachments/assets/a6003d53-f219-45b4-b541-1c161b13fc07)

I have connected the mesh with the pipe and started the server in Blender. However, I receive messages like this in both Grasshoppers and Blender. I don't know what the issue is. Before then, I was using the old version from your Github, and it worked a few times, yet it didn't work a few days ago. May I know how I can confirm the pipe is not busy? Also when I paste your updated code into blender, it comes up with the blender message shown in the attached blender console screenshot. Such is not happened when I am using the old version of named pipe code. Attached is the grasshopper interface showing the error message and the blender console. Thank you! Your work in Github is amazing!!!!!!!!!!!!!!!!!!!!

**Comment by sean1832** [comment]
Hi,

When using named pipes, it's important to ensure that only one server (receiving end) is active at a time. A named pipe can only be accessed by a single server and a single client (sending end) connection. If you enable the server in Grasshopper, you cannot also enable the server in Blender simultaneously. If both servers are active, the pipe will be busy, leading to the issues you're experiencing.

To resolve this:
1. Ensure that you start the server only in one application (either Grasshopper or Blender).
2. The client in the other application should then connect to this server.

If the pipe is already blocked:
1. Stop all servers in both Grasshopper and Blender.
2. Restart only one server and attempt to send a message from the client.

If this does not resolve the issue, the easiest solution is to restart both programs and ensure only one server is active at a time.

I apologize for any confusion caused by the example file. I will update it to make this clearer.

Let me know how it goes. Cheers.

![image](https://github.com/user-attachments/assets/201f66f2-b1af-4976-a3b5-fc8340cf4114)

**Comment by sean1832** [comment]
You can try this grasshopper script for pipe connection between grasshopper and blender.
[gh-blender-pipe.zip](https://github.com/user-attachments/files/16823911/gh-blender-pipe.zip)

**Comment by twoobao** [comment]
[錄製內容 2024-08-31 163521.zip](https://github.com/user-attachments/files/16824001/2024-08-31.163521.zip)
This is the video of I tried to send through grasshopper and just start the server in Blender, however it still shows the error in the Blender console. May I know if I am doing the right thing that I restart by give "FALSE" to the toggle and also "STOP" in blender, I then also try to only send string to the byte input of the client pipe node in grasshopper yet it is still giving the same error. Thanks alot!

**Comment by sean1832** [comment]
Did you restart both program? What if you change the pipe name to something else for both grasshopper and blender?

**Comment by twoobao** [comment]
Hi, It works! The pipe could be used. Regarding the pipe_server.py I would like to ask as I have tried the old version pipe_server.py with modification and due to more control of the mesh data, and now when i run the script, there are also the "Pipe Server" in the right side bar. And the code could only be use when the server is started by "Pipe Server" tab but not the one "Portal", may I know if there is anything I could make the present pipe_server.py has more control on the mesh data. Since as I run the old version python file, only "Pipe Server" tab has the control of the server but not `"Portal". Thanks for your detailed instructions! 

![螢幕擷取畫面 2024-08-31 212926](https://github.com/user-attachments/assets/966133fd-8d0e-4f36-9253-6d25e937e769)

**Comment by sean1832** [comment]
Hi,
May I understand that you want to have more custom control over the mesh data and you want help on where to handel the mesh in the python script?

If so, here is where you can add more custom logic to handle incomming data. The incomming data is basically a JSON. [pipe_server.py L18-L31](https://github.com/sean1832/Portal/blob/75a81188b3ee689532f92b246b4fc5bae1cfcb20/Example/python-blender/pipe-server.py#L18-L31)
```python
class DataHandler:
    @staticmethod
    def handle_data(data, data_type):
        """Handle parsed data in string, this is the main place to implement your logic"""
        try:
            if data_type == "Text":
                print(f"Received message: {data}")
            elif data_type == "Mesh":
                message_dics = json.loads(data)
                for i, item in enumerate(message_dics):
                    vertices, faces, uvs = MeshHandler.deserialize_mesh(item)
                    MeshHandler.create_or_replace_mesh(f"object_{i}", vertices, faces)
        except json.JSONDecodeError:
            print(f"Unsupported data: {data}")
```

Here is where you deserialize the mesh and construct mesh. [pipe_server.py L34-L58](https://github.com/sean1832/Portal/blob/75a81188b3ee689532f92b246b4fc5bae1cfcb20/Example/python-blender/pipe-server.py#L34-L58)
```python
class MeshHandler:
    @staticmethod
    def deserialize_mesh(data):
        """Deserialize mesh data from json string"""
        vertices = [(v["X"], v["Y"], v["Z"]) for v in data["Vertices"]]
        faces = [tuple(face_list) for face_list in data["Faces"]]
        uvs = [(uv["X"], uv["Y"]) for uv in data["UVs"]]
        return vertices, faces, uvs

    @staticmethod
    def create_or_replace_mesh(object_name, vertices, faces):
        obj = bpy.data.objects.get(object_name)
        new_mesh_data = bpy.data.meshes.new(f"{object_name}_mesh")
        new_mesh_data.from_pydata(vertices, [], faces)
        new_mesh_data.update()

        if obj and obj.type == "MESH":
            old_mesh = obj.data
            obj.data = new_mesh_data
            bpy.data.meshes.remove(old_mesh)
        else:
            new_object = bpy.data.objects.new(object_name, new_mesh_data)
            bpy.context.collection.objects.link(new_object)

        new_mesh_data.update()
```

Cheers.

**Comment by twoobao** [comment]
Yes I have modified those parts from the old version py script from you and it works . As you see in the video, everything could only be work in the "Pipe server" tab once I run the code but not "Portal".  My question is if there is any way I could integrate this part (mesh handler) into "Portal" but not "Pipe server" so I could control (start , stop server) everything in "Portal". Thanks alot!!!
[螢幕錄製 2024-09-01 223745.zip](https://github.com/user-attachments/files/16829308/2024-09-01.223745.zip)

**Comment by sean1832** [comment]
Hi,
You can customize the logic in the new version of the Blender Portal plugin by referencing the code between lines 73 and 143 in `handlers.py`. You can view this at [handlers.py L73-L143](https://github.com/sean1832/Portal.blender/blob/main/portal/handlers.py#L73-L143).

### Modification Options:

#### Option 1: Direct Modification
After installing the Blender plugin, navigate to the plugin script located at:
`C:\Users\<YOUR_USER_NAME>\AppData\Roaming\Blender Foundation\Blender\<BLENDER_VERSION>\scripts\addons\portal\handlers.py`
You can edit this file using a text editor like [VSCode](https://code.visualstudio.com/).

#### Option 2: Modify from Source
1. Clone the repository:
   ```
   git clone https://github.com/sean1832/Portal.blender
   cd Portal.blender/portal
   ```
2. Open and modify the `handlers.py` using VSCode:
   ```
   code handlers.py
   ```
3. After modifications, zip the `portal` folder and reinstall the plugin in Blender.

#### Option 3: Experimental Portable Script
[Version 0.0.3](https://github.com/sean1832/Portal.blender/releases/tag/0.0.3) of Portal.blender includes an experimental portable script that consolidates everything into a single Python file. This file can be directly pasted into Blender's text editor to run. Note: This script is not optimized for readability and is experimental.

**Comment by twoobao** [comment]
Thank you so much for the helpful suggestions that quickly answered my questions. It's made a big difference and I'm grateful for your assistance. Have a nice day!

**Comment by sean1832** [comment]
No problem mate. Feel free to open more issues if you encounter other problems. Cheers.
